version: 2.1

orbs:
  ssh-deployment: singularitynet/ssh-deployment@2.0.0

jobs:
  cntk-image-recon:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_CNTK_IMAGE_RECON}
          ssh-user: ${SSH_USER_CNTK_IMAGE_RECON}
          service-dir: "services/cntk-image-recon"
          mainnet-port: "7004"
          testnet-port: "7054"
          run-command: "source '/cntk/activate-cntk';python3 run_image_recon_service.py --ssl"
          test-command: "sleep 60;source '/cntk/activate-cntk';python3 test_image_recon_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/cntk-image-recon/Dockerfile"
          docker-no-cache: true
          docker-image: "cntk_image_recognition"
          docker-container: "CNTK_IMAGE_RECON"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_CNTK_IMAGE_RECON}
  deepfakes-faceswap:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_DEEPFAKES_FACESWAP}
          ssh-user: ${SSH_USER_DEEPFAKES_FACESWAP}
          service-dir: "services/deepfakes-faceswap"
          mainnet-port: "7060"
          testnet-port: "7061-7062"
          run-command: "python3 run_deepfakes_faceswap_service.py --ssl"
          test-command: "sleep 60;python3 test_deepfakes_faceswap_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/deepfakes-faceswap/Dockerfile"
          docker-no-cache: true
          docker-image: "deepfakes_faceswap"
          docker-container: "DEEPFAKES_FACESWAP"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs -v ~/storage:/opt/storage"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_DEEPFAKES_FACESWAP}
  i3d-video-action-recognition:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_I3D_VIDEO_ACTION_RECON}
          ssh-user: ${SSH_USER_I3D_VIDEO_ACTION_RECON}
          service-dir: "services/i3d-video-action-recognition"
          mainnet-port: "7005"
          testnet-port: "7055"
          run-command: "python3 run_video_action_recon_service.py --ssl"
          test-command: "sleep 60;python3 test_video_action_recon_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/i3d-video-action-recognition/Dockerfile"
          docker-no-cache: true
          docker-image: "i3d_video_action_recognition"
          docker-container: "I3D_VIDEO_ACTION_RECON"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_I3D_VIDEO_ACTION_RECON}
  places365-scene-recognition:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_PLACES365_SCENE_RECOGNITION}
          ssh-user: ${SSH_USER_PLACES365_SCENE_RECOGNITION}
          service-dir: "services/places365-scene-recognition"
          mainnet-port: "7019"
          testnet-port: "7079"
          run-command: "python3 run_scene_recognition_service.py --ssl"
          test-command: "sleep 60;python3 test_scene_recognition_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/places365-scene-recognition/Dockerfile"
          docker-no-cache: true
          docker-image: "places365_scene_recognition"
          docker-container: "PLACES365_SCENE_RECOGNITION"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_PLACES365_SCENE_RECOGNITION}
  pneumonia-diagnosis:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_PNEUMONIA_DIAGNOSIS}
          ssh-user: ${SSH_USER_PNEUMONIA_DIAGNOSIS}
          service-dir: "services/pneumonia-diagnosis"
          mainnet-port: "7072"
          testnet-port: "7062"
          run-command: "python3 run_pneumonia_diagnosis_service.py --ssl"
          test-command: "sleep 60;python3 test_pneumonia_diagnosis_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/pneumonia-diagnosis/Dockerfile"
          docker-no-cache: true
          docker-image: "pneumonia_diagnosis"
          docker-container: "PNEUMONIA_DIAGNOSIS"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_PNEUMONIA_DIAGNOSIS}
  real-time-voice-cloning:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_VOICE_CLONING}
          ssh-user: ${SSH_USER_VOICE_CLONING}
          service-dir: "services/real-time-voice-cloning"
          mainnet-port: "7064"
          testnet-port: "7065"
          run-command: "python3 run_voice_cloning_service.py --ssl"
          test-command: "sleep 60;python3 test_voice_cloning_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/real-time-voice-cloning/Dockerfile"
          docker-no-cache: true
          docker-image: "voice_cloning"
          docker-container: "VOICE_CLONING"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_VOICE_CLONING}
  s2vt-video-captioning:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_S2VT_VIDEO_CAPTIONING}
          ssh-user: ${SSH_USER_S2VT_VIDEO_CAPTIONING}
          service-dir: "services/s2vt-video-captioning"
          mainnet-port: "7006"
          testnet-port: "7056"
          run-command: "python run_video_cap_service.py --ssl"
          test-command: "sleep 60;python test_video_cap_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/s2vt-video-captioning/Dockerfile"
          docker-no-cache: true
          docker-image: "s2vt_video_captioning"
          docker-container: "S2VT_VIDEO_CAPTIONING"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_S2VT_VIDEO_CAPTIONING}
  siggraph-colorization:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_SIGGRAPH_COLORIZATION}
          ssh-user: ${SSH_USER_SIGGRAPH_COLORIZATION}
          service-dir: "services/siggraph-colorization"
          mainnet-port: "7084"
          testnet-port: "7085"
          run-command: "python3 run_colorize_service.py --ssl"
          test-command: "sleep 60;python3 test_colorize_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/siggraph-colorization/Dockerfile"
          docker-no-cache: true
          docker-image: "siggraph_colorization"
          docker-container: "SIGGRAPH_COLORIZATION"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_SIGGRAPH_COLORIZATION}
  sound-spleeter:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_SOUND_SPLEETER}
          ssh-user: ${SSH_USER_SOUND_SPLEETER}
          service-dir: "services/sound-spleeter"
          mainnet-port: "7066"
          testnet-port: "7067"
          run-command: "python3 run_sound_spleeter_service.py --ssl"
          test-command: "sleep 60;python3 test_sound_spleeter_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/sound-spleeter/Dockerfile"
          docker-no-cache: true
          docker-image: "sound_spleeter"
          docker-container: "SOUND_SPLEETER"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_SOUND_SPLEETER}
  yolov3-object-detection:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_YOLOv3_OBJECT_DETECTION}
          ssh-user: ${SSH_USER_YOLOv3_OBJECT_DETECTION}
          service-dir: "services/yolov3-object-detection"
          mainnet-port: "7007"
          testnet-port: "7057"
          run-command: "python3 run_object_detection_service.py --ssl"
          test-command: "sleep 60;python3 test_object_detection_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/yolov3-object-detection/Dockerfile"
          docker-no-cache: true
          docker-image: "yolov3_object_detection"
          docker-container: "YOLOv3_OBJECT_DETECTION"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_YOLOv3_OBJECT_DETECTION}
  zeta36-chess-alpha-zero:
    docker:
      - image: circleci/python:3.6.6-node
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST_CHESS_ALPHA_ZERO}
          ssh-user: ${SSH_USER_CHESS_ALPHA_ZERO}
          service-dir: "services/zeta36-chess-alpha-zero"
          mainnet-port: "7008"
          testnet-port: "7058"
          run-command: "python3.6 run_alpha_zero_service.py --ssl"
          test-command: "sleep 60;python3.6 test_alpha_zero_service.py auto"
          docker-test-files: "Dockerfile, requirements.txt"
          docker-file-path: "services/zeta36-chess-alpha-zero/Dockerfile"
          docker-no-cache: true
          docker-image: "zeta36_chess_alpha_zero"
          docker-container: "CHESS_ALPHA_ZERO"
          docker-nvidia: true
          docker-volumes: "-v ~/singnet/.certs:/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-version: ${CI_SNETD_VERSION}
          daemon-pk: ${PK_CHESS_ALPHA_ZERO}

workflows:
  build_deploy_dnn_services:
    jobs:
      - cntk-image-recon
#      - deepfakes-faceswap
      - i3d-video-action-recognition
      - places365-scene-recognition
#      - pneumonia-diagnosis
      - real-time-voice-cloning
      - s2vt-video-captioning
#      - siggraph-colorization
      - sound-spleeter
      - yolov3-object-detection
      - zeta36-chess-alpha-zero
